# Generated by Django 5.2.1 on 2025-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='algorithm',
            field=models.CharField(default='AES', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='decrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
