# Generated by Django 5.2.1 on 2025-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_algorithm_message_decrypted_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='algorithm',
            field=models.CharField(default='AES', max_length=50),
        ),
    ]
